server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/oauth2/**,/login/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**

        - id: course-service-quizzes
          uri: lb://course-service
          predicates:
            - Path=/quizzes/**

        - id: course-service-questions
          uri: lb://course-service
          predicates:
            - Path=/questions/**

        - id: course-service-attempts
          uri: lb://course-service
          predicates:
            - Path=/attempts/**

        - id: course-service-modules
          uri: lb://course-service
          predicates:
            - Path=/modules/**

        - id: course-service-lessons
          uri: lb://course-service
          predicates:
            - Path=/lessons/**

        - id: course-service-assignments
          uri: lb://course-service
          predicates:
            - Path=/assignments/**

        - id: course-service-submissions
          uri: lb://course-service
          predicates:
            - Path=/submissions/**

        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/enrollments/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: admin-server
          uri: lb://admin-server
          predicates:
            - Path=/admin/**
