server:
  port: 9090

spring:
  application:
    name: admin-server
  boot:
    admin:
      context-path: /admin
      ui:
        public-url: http://localhost:9090/admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true